_wandb:
    value:
        cli_version: 0.23.1
        e:
            vxqxk06ptms40rv7lyywe4n2353hqj3u:
                codePath: Project_eda.ipynb
                codePathLocal: Project_eda.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "487153012736"
                        used: "225980514304"
                email: m.bebej6@gmail.com
                executable: C:\Users\mbebe\PycharmProjects\ZNEUS_test\.venv\Scripts\python.exe
                git:
                    commit: 30901f50c2d2595f69303417f5ada76a903ee00f
                    remote: https://github.com/MatoBebej/mb_ms_zneus2.git
                gpu: NVIDIA GeForce RTX 3070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5120
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070 Laptop GPU
                      uuid: GPU-ac9ac1ef-aba8-134d-a56e-498063d63d68
                host: MatejPC
                memory:
                    total: "16371519488"
                os: Windows-11-10.0.26100-SP0
                program: Project_eda.ipynb
                python: CPython 3.13.7
                root: C:\Users\mbebe\Desktop\znus_2_project
                startedAt: "2025-12-07T21:02:38.333950Z"
                writerId: vxqxk06ptms40rv7lyywe4n2353hqj3u
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
dropout:
    value: 0.3
epochs:
    value: 10
learning_rate:
    value: 0.001
model:
    value: CustomResNet
patience:
    value: 100
weight_decay:
    value: 0.0001
